### ISSUE TITLE
What are the experiments?

### ISSUE THREAD

**Issue by rgga-16** [UW-ERSL/MaTruss#1]
Hi! I'm interested in your work. What do the [expt1_3d.ipynb] and [expt1_Area_Mass.ipynb] notebooks test out?

**Comment by sakethsridhara** [comment]
Hi,

The 3D example (added recently) demonstrates an extension of the proposed method to 3D (spatial) truss systems. 
The Area Mass examples demonstrate area optimization under mass constraints. Most of the constraints can be easily switched ON or OFF based on whether you'd like them to be active or not. You can refer to the manuscript https://arxiv.org/pdf/2112.12566.pdf for more details.
